name: Proactive Forward Merge

on:
  push:
    branches:
      - 'release-9.5.1'
      - 'release-9.5.1.1'
      - 'release-9.6.0'

jobs:
  forward-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits for comparison

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      
